# Generated by Django 5.0.4 on 2024-05-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investments',
            name='date',
        ),
        migrations.AddField(
            model_name='investments',
            name='expected_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='investments',
            name='invested_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='investments',
            name='last_viewed',
            field=models.DateField(null=True),
        ),
    ]
