# Generated by Django 5.0.4 on 2024-05-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('failed', 'FAILED'), ('success', 'SUCCESS')], default='pending', max_length=10),
        ),
    ]
