# Generated by Django 5.0.4 on 2024-05-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_transactions_blockchain_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='crytp_api_uuid',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
