# Generated by Django 5.0.4 on 2024-05-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_transactions_crytp_api_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='token',
            field=models.CharField(choices=[('btc', 'btc'), ('eth', 'eth'), ('usdt', 'trc20/usdt'), ('trx', 'trx')], default='btc', max_length=10),
        ),
    ]
